name: mportal-with_db

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
     - .mportal-env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      interval: 5s
      retries: 10
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    networks:
      - nginx-network

  mportal:
    build: .
    container_name: mportal
    env_file:
     - .mportal-env
    ports:
      - "8002:8002"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_HOST: mariadb
      VIRTUAL_HOST: portal.ceyraud.com
      LETSENCRYPT_HOST: portal.ceyraud.com
    volumes:
      - init:/usr/vol
    networks:
      - nginx-network
      

volumes:
  db_data:
  init:
networks:
 nginx-network:
  external: true